In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [ ]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.index.tolist()

['x', 'y', 'z']

In [ ]:
df.shape

(3, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
df.columns.tolist()

['A', 'B', 'C']

In [ ]:
df.describe().T

   count  mean  std  min  25%  50%  75%  max
A    3.0   4.0  3.0  1.0  2.5  4.0  5.5  7.0
B    3.0   5.0  3.0  2.0  3.5  5.0  6.5  8.0
C    3.0   6.0  3.0  3.0  4.5  6.0  7.5  9.0

In [ ]:
df["B"].unique()

array([2, 5, 8])

In [ ]:
df[["A", "B"]]

   A  B
x  1  2
y  4  5
z  7  8

In [ ]:
df.size

9

# Yuklab olish

In [ ]:
df = pd.read_csv("./titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.columns = df.columns.str.lower()

df = df.rename(columns={"passengerid":"passenger_id"})

df.head()

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Filtering

In [ ]:
df[(df["age"] == 22) & (df["sex"] == "female") ]

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.0,0,0,347081,7.7500,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
289,290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.7500,NaN,Q
323,324,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.0,1,1,248738,29.0000,NaN,S
356,357,1,1,"Bowerman, Miss. Elsie Edith",female,22.0,0,1,113505,55.0000,E33,S
376,377,1,3,"Landergren, Miss. Aurora Adelia",female,22.0,0,0,C 7077,7.2500,NaN,S
474,475,0,3,"Strandberg, Miss. Ida Sofia",female,22.0,0,0,7553,9.8375,NaN,S
539,540,1,1,"Frolicher, Miss. Hedwig Margaritha",female,22.0,0,2,13568,49.5000,B39,C
554,555,1,3,"Ohman, Miss. Velin",female,22.0,0,0,347085,7.7750,NaN,S
608,609,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",female,22.0,1,2,SC/Paris 2123,41.5792,NaN,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.0,0,0,113781,151.5500,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S

In [ ]:
df.sample(10)

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,age
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C,NaN
738,739,0,3,"Ivanoff, Mr. Kanio",male,NaN,0,0,349201,7.8958,NaN,S,NaN
620,621,0,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,NaN
173,174,0,3,"Sivola, Mr. Antti Wilhelm",male,21.0,0,0,STON/O 2. 3101280,7.9250,NaN,S,NaN
227,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.2500,NaN,S,NaN
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S,NaN
350,351,0,3,"Odahl, Mr. Nils Martin",male,23.0,0,0,7267,9.2250,NaN,S,NaN
654,655,0,3,"Hegarty, Miss. Hanora ""Nora""",female,18.0,0,0,365226,6.7500,NaN,Q,NaN
143,144,0,3,"Burke, Mr. Jeremiah",male,19.0,0,0,365222,6.7500,NaN,Q,NaN
613,614,0,3,"Horgan, Mr. John",male,NaN,0,0,370377,7.7500,NaN,Q,NaN

In [ ]:
valid  =  df["parch"] == 0

df[valid]

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,22,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,22,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,22,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,22,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,22,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,22,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22,1,0,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,22,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,22,0,0,370376,7.7500,NaN,Q

In [ ]:
df.query("embarked == 'S' ")

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,22,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,22,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,22,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,22,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,22,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,22,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,22,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,22,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22,1,0,W./C. 6607,23.4500,NaN,S

#  Filtering

In [ ]:
df.sort_values(by=["passenger_id", "fare"], ascending=[1, 0])

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Accessing the data

In [ ]:
df["fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

In [ ]:
df.loc[5:8 ,["passenger_id", "name", "age"]]

   passenger_id                                               name  age
5             6                                   Moran, Mr. James   22
6             7                            McCarthy, Mr. Timothy J   22
7             8                     Palsson, Master. Gosta Leonard   22
8             9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   22

In [ ]:
df.iloc[:5, [2, 3]]

   pclass                                               name
0       3                            Braund, Mr. Owen Harris
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2       3                             Heikkinen, Miss. Laina
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       3                           Allen, Mr. William Henry

In [ ]:
df.iloc[2:5, 5] = 29

df.loc[:5]

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,29.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,29.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,29.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.0,0,0,330877,8.4583,NaN,Q

In [ ]:
df[df["cabin"].isna()]

,passenger_id,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,29.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,29.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.0,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df = pd.read_excel("./olympics-data.xlsx",engine='openpyxl')

df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
df.dropna(inplace=True)

In [5]:
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21

In [6]:
df["born_date"] = pd.to_datetime(df["born_date"])
df["died_date"] = pd.to_datetime(df["died_date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10794 entries, 2 to 141190
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   athlete_id    10794 non-null  int64
 1   name          10794 non-null  object
 2   born_date     10794 non-null  datetime64[ns]
 3   born_city     10794 non-null  object
 4   born_region   10794 non-null  object
 5   born_country  10794 non-null  object
 6   NOC           10794 non-null  object
 7   height_cm     10794 non-null  float64
 8   weight_kg     10794 non-null  float64
 9   died_date     10794 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(5)
memory usage: 1.2+ MB

In [7]:
df["smth"] =df["height_cm"] * df["weight_kg"]

df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,smth
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,13908.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,10752.0
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29,12110.0
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15,10855.0
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21,22250.0

In [8]:
df = df.drop("smth", axis=1)

df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,2010-07-29
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,2019-09-15
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,2006-07-21

In [9]:
df = df.loc[:, df.columns[:-1]]

df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0

In [10]:
df["status"] = df["height_cm"].apply(lambda x: "Tall" if x >= 180 else "Standard" if x >= 165 and x < 180 else "Short")

df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,status
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,Standard
107,108,Anders Nielsen,1967-02-24,Cape Town,Western Cape,RSA,Great Britain,173.0,70.0,Standard
258,259,Tonny Maringgi,1959-06-10,Kendari,Sulawesi Tenggara,INA,Indonesia,167.0,65.0,Standard
300,301,Jackson Fear,1978-01-13,Sydney,New South Wales,AUS,Australia,178.0,125.0,Standard

# Merging and Concat

In [ ]:
data = [['LCHouse1', 1, 1], ['LCHouse1', 2, 10], ['LCHouse1', 3, 5], ['LCHouse2', 1, 2], ['LCHouse2', 2, 2], ['LCHouse3', 4, 1]]
warehouse = pd.DataFrame(data, columns=['name', 'product_id', 'units']).astype({'name':'object', 'product_id':'Int64', 'units':'Int64'})

data = [[1, 'LC-TV', 5, 50, 40], [2, 'LC-KeyChain', 5, 5, 5], [3, 'LC-Phone', 2, 10, 10], [4, 'LC-T-Shirt', 4, 10, 20]]
products = pd.DataFrame(data, columns=['product_id', 'product_name', 'Width', 'Length', 'Height']).astype({'product_id':'Int64', 'product_name':'object', 'Width':'Int64', 'Length':'Int64', 'Height':'Int64'})


result = pd.merge(warehouse, products, on="product_id", how="inner")

result

       name  product_id  units product_name  Width  Length  Height
0  LCHouse1           1      1        LC-TV      5      50      40
1  LCHouse1           2     10  LC-KeyChain      5       5       5
2  LCHouse1           3      5     LC-Phone      2      10      10
3  LCHouse2           1      2        LC-TV      5      50      40
4  LCHouse2           2      2  LC-KeyChain      5       5       5
5  LCHouse3           4      1   LC-T-Shirt      4      10      20

In [ ]:
data1 = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df1 = pd.DataFrame(data1)


data2 = {
    'A': [7, 8, 9],
    'B': [10, 11, 12]
}
df2 = pd.DataFrame(data2)

result = pd.concat([df1, df2], axis=0)

result

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [11]:
df1 = df[df["NOC"] == "France"]

df2 = df[df["NOC"] == "Australia"]

result = pd.concat([df1, df2], axis=0)

result["NOC"].unique()

array(['France', 'Australia'], dtype=object)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.drop_duplicates()

# Aggregate Functions

In [ ]:
df["born_region"].value_counts()

born_region
England               443
Budapest              245
California            195
New York              153
Moskva                151
                     ...
Rovigo                  1
Teramo                  1
Sükhbaatar              1
Slovenska Bistrica      1
Sennar                  1
Name: count, Length: 1351, dtype: int64

In [19]:
df[df["born_country"] == "USA"]["born_region"].value_counts().reset_index()

             born_region  count
0             California    195
1               New York    153
2          Massachusetts    109
3           Pennsylvania    108
4               Illinois    104
5                  Texas     65
6             New Jersey     64
7              Minnesota     62
8               Michigan     51
9                   Ohio     47
10              Oklahoma     32
11                Oregon     28
12            Washington     27
13               Indiana     26
14             Louisiana     25
15                  Iowa     25
16                Kansas     23
17           Mississippi     23
18           Connecticut     22
19              Missouri     22
20             Wisconsin     21
21               Georgia     18
22              Maryland     17
23        North Carolina     15
24              Kentucky     15
25              Virginia     15
26               Alabama     14
27               Florida     14
28                  Utah     14
29              Arkansas     13
30              Colorado     13
31  District of Columbia     13
32              Nebraska     12
33                 Maine     11
34          Rhode Island     10
35               Arizona     10
36               Hawaiʻi      9
37             Tennessee      8
38               Vermont      8
39               Montana      7
40          South Dakota      7
41         New Hampshire      6
42            New Mexico      4
43                 Idaho      4
44          North Dakota      4
45        South Carolina      3
46         West Virginia      3
47              Delaware      3
48               Wyoming      3
49                Alaska      1
50                Nevada      1

In [20]:
df.groupby("born_country")[["height_cm", "weight_kg"]].agg(["mean", "sum"]).reset_index()

    born_country   height_cm           weight_kg
                        mean      sum       mean      sum
0            AFG  163.000000    326.0  62.500000    125.0
1            ALG  174.454545   1919.0  68.727273    756.0
2            ANG  178.000000    712.0  72.500000    290.0
3            ARG  176.503497  25240.0  75.762238  10834.0
4            ARM  171.625000   1373.0  72.750000    582.0
..           ...         ...      ...        ...      ...
153          VEN  174.266667   2614.0  69.800000   1047.0
154          VIE  172.000000    688.0  70.500000    282.0
155       Vienna  173.500000    347.0  78.000000    156.0
156          ZAM  176.538462   2295.0  70.692308    919.0
157          ZIM  173.333333   1040.0  72.333333    434.0

[158 rows x 5 columns]

In [24]:
df.groupby("born_country").agg({
    "height_cm":"max",
    "weight_kg":"min"
}).reset_index()

    born_country  height_cm  weight_kg
0            AFG      166.0       62.0
1            ALG      188.0       51.0
2            ANG      189.0       69.0
3            ARG      200.0       49.0
4            ARM      182.0       60.0
..           ...        ...        ...
153          VEN      187.0       53.0
154          VIE      182.0       62.0
155       Vienna      183.0       72.0
156          ZAM      187.0       48.0
157          ZIM      187.0       61.0

[158 rows x 3 columns]

In [28]:
df.groupby('NOC')["athlete_id"].count().reset_index().sort_values(by="athlete_id", ascending=False)

                        NOC  athlete_id
192           United States        1551
143                  Poland         683
170            Soviet Union         676
65                   France         559
74            Great Britain         508
..                      ...         ...
131                   Niger           1
43                   Cyprus           1
127                   Nauru           1
47   Czechoslovakia Hungary           1
139                Paraguay           1

[203 rows x 2 columns]

In [31]:
coffee_df = pd.read_csv("./coffee.csv")

In [32]:
coffee_df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [45]:
result = coffee_df.groupby("Day")["Units Sold"].sum().reset_index().sort_values(by="Units Sold", ascending=False)

result["rating"] = result["Units Sold"].rank(ascending=False, method="dense")

result

         Day  Units Sold  rating
0     Friday          80     1.0
2   Saturday          80     1.0
3     Sunday          80     1.0
4   Thursday          70     2.0
6  Wednesday          60     3.0
5    Tuesday          50     4.0
1     Monday          40     5.0

In [46]:
result["sum_total"] = result["Units Sold"].cumsum()

result

         Day  Units Sold  rating  sum_total
0     Friday          80     1.0         80
2   Saturday          80     1.0        160
3     Sunday          80     1.0        240
4   Thursday          70     2.0        310
6  Wednesday          60     3.0        370
5    Tuesday          50     4.0        420
1     Monday          40     5.0        460

In [47]:
result["yesterday_sold"] = result["Units Sold"].shift(1)

result

         Day  Units Sold  rating  sum_total  yesterday_sold
0     Friday          80     1.0         80             NaN
2   Saturday          80     1.0        160            80.0
3     Sunday          80     1.0        240            80.0
4   Thursday          70     2.0        310            80.0
6  Wednesday          60     3.0        370            70.0
5    Tuesday          50     4.0        420            60.0
1     Monday          40     5.0        460            50.0

In [56]:
df.groupby(df["born_date"].dt.year)["athlete_id"].count().reset_index().sort_values(by="athlete_id", ascending=False)

     born_date  athlete_id
75        1937         308
76        1938         297
70        1932         294
77        1939         292
73        1935         290
..         ...         ...
7         1869           1
6         1868           1
3         1862           1
2         1855           1
137       2002           1

[138 rows x 2 columns]

In [58]:
df["rank"] = df["height_cm"].rank(ascending=False, method="dense")

df[df["rank"] ==  1]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,status,rank
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,Tall,1.0

In [ ]:
transform()

In [76]:
data = [[1, 'Joe', 85000, 1], [2, 'Henry', 80000, 2], [3, 'Sam', 60000, 2], [4, 'Max', 90000, 1], [5, 'Janet', 69000, 1], [6, 'Randy', 85000, 1], [7, 'Will', 70000, 1]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'departmentId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'departmentId':'Int64'})
data = [[1, 'IT'], [2, 'Sales']]
department = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})


df = pd.merge(employee, department, left_on="departmentId", right_on="id", how="inner")

df["rank"] = df.groupby("name_y")["salary"].transform("rank", method="min")

df[df["rank"] <= 3]

   id_x name_x  salary  departmentId  id_y name_y  rank
0     1    Joe   85000             1     1     IT   3.0
1     2  Henry   80000             2     2  Sales   2.0
2     3    Sam   60000             2     2  Sales   1.0
4     5  Janet   69000             1     1     IT   1.0
5     6  Randy   85000             1     1     IT   3.0
6     7   Will   70000             1     1     IT   2.0